name: weekly-renovate-bot-trigger

#            ?????????????? minute (0 - 59)
#            ? ?????????????? hour (0 - 23)
#            ? ? ?????????????? day of the month (1 - 31)
#            ? ? ? ?????????????? month (1 - 12)
#            ? ? ? ? ?????????????? day of the week (0 - 6)
#            ? ? ? ? ?                                   
#            ? ? ? ? ?
#            ? ? ? ? ?
#            ? ? ? ? ?
on: #        ? ? ? ? ?
  schedule: #? ? ? ? ?
    - cron: "1 0 * * 0"  # Every Sunday at 0:01

jobs:
  weekly-renovate-call:
    uses: ./.github/workflows/renovate-bot-run.yml
    secrets: inherit
    with:
        renovate_repository_filter: "simatic-ax/Generators"
